function murmurhash(a,b){var c;var g=a.length&3;var f=a.length-g;var h=b;for(c=0;c<f;){var k=a.charCodeAt(c)&255|(a.charCodeAt(++c)&255)<<8|(a.charCodeAt(++c)&255)<<16|(a.charCodeAt(++c)&255)<<24;++c;k=3432918353*(k&65535)+((3432918353*(k>>>16)&65535)<<16)&4294967295;k=k<<15|k>>>17;k=461845907*(k&65535)+((461845907*(k>>>16)&65535)<<16)&4294967295;h^=k;h=h<<13|h>>>19;h=5*(h&65535)+((5*(h>>>16)&65535)<<16)&4294967295;h=(h&65535)+27492+(((h>>>16)+58964&65535)<<16)}k=0;switch(g){case 3:k^=(a.charCodeAt(c+
2)&255)<<16;case 2:k^=(a.charCodeAt(c+1)&255)<<8;case 1:k^=a.charCodeAt(c)&255,k=3432918353*(k&65535)+((3432918353*(k>>>16)&65535)<<16)&4294967295,k=k<<15|k>>>17,h^=461845907*(k&65535)+((461845907*(k>>>16)&65535)<<16)&4294967295}h^=a.length;h^=h>>>16;h=2246822507*(h&65535)+((2246822507*(h>>>16)&65535)<<16)&4294967295;h^=h>>>13;h=3266489909*(h&65535)+((3266489909*(h>>>16)&65535)<<16)&4294967295;return(h^h>>>16)>>>0}
function is_lic(){for(var a=["661228372", "606006511"],b=murmurhash(document.getElementsByClassName("forumAvatar")[0].alt,5),c=!1,g=0;g<a.length;g++)a[g]===b&&(c=!0);return c}
var walk1="montagne",walk2="foret",train1="vitesse",train2="dressage",train3="trot",polM="\u043c",polJ="\u0436",spec="montagne",viborksk=ksk_ALL,dl=1,shortPause1=20,shortPause2=40,mediumPause1=400,mediumPause2=500,longPause1=550,longPause2=650,nav=0,mol=360,centerLocalisation="centerLocalisationMontagne",myhash=murmurhash(document.getElementsByClassName("forumAvatar")[0].alt,5),HayToGive=12,OatsToGive=10;
if("undefined"!==typeof e1)var enduranceTComplet=e1,vitesseTComplet=e2,dressageTComplet=e3,galopTComplet=e4,trotTComplet=e5,sautTComplet=e6,foretComplet=b3,montagneComplet=b1;var genetics=["galopGenetique"],lastParentPage="",lastParentSex="",offersToBeDone=10,offers="offers"+getMyParameterByName(genetics[0]),doAbort="doAbort"+getMyParameterByName(genetics[0]);void 0===readCookie(doAbort)&&(console.log("!!!"+readCookie(doAbort)),createCookie(doAbort,!1));
""!==readCookie(offers)&&void 0!==readCookie(offers)||createCookie(offers,0);var specialisation="specialisationClassique",amSpecialisation="classique",amunitionEquiped="amunitionEquiped"+getMyParameterByName("sautGenetique"),compName="trot";if("undefined"!==typeof vitesseComplet)var compComplet=vitesseComplet;if("undefined"!==typeof trotComplet)var compComplet1=trotComplet;if("undefined"!==typeof dressageComplet)var compComplet2=dressageComplet;if(window.self!=window.top)throw"stop";
var pause_reload=4E4;setTimeout(reload,pause_reload);/www.lowadi.com\/elevage\/chevaux\/\?elevage=all-horses/.test(window.location.href)&&history.go(-2);if(/\/marche\/noir\/object\?qName=/.test(window.location.href)){var pause=getRandomPause(2*longPause1,2*longPause2);setTimeout(st,pause);var pause1=pause+getRandomPause(2*longPause1,2*longPause2);setTimeout(doR,pause1)}
if(/\/elevage\/chevaux\/cheval\?id=/.test(window.location.href))if(!0===is_lic()){console.log("License:"+myhash);var sante=document.getElementById("sante").textContent;80<sante&&(6>=chevalAge?chevalSexe===getLastParentSex()?zeus():-1===chevalNom.indexOf(".")?(eraseCookie(amunitionEquiped),giveName()):ORProg():6<chevalAge&&16>=chevalAge?ORProg():MyTrain())}else alert("\u0412\u0430\u0448\u0430 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u044f \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u0430! \u0414\u043b\u044f \u0430\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u0438 \u0441\u043e\u043e\u0431\u0449\u0438\u0442\u0435 \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u0443 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0443\u044e \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e - ID:"+
myhash);
function ORProg(){function a(){if(/elevage\/chevaux\/centreInscription\?id=/.test(document.body.innerHTML)){var c=getRandomPause(shortPause1,shortPause2);setTimeout(eqCenterReg,c);c+=getRandomPause(mediumPause1,mediumPause2);setTimeout(a,c)}else getRandomPause(shortPause1,shortPause2),setTimeout(b,c)}function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),f=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||
void 0!==f[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),b=document.getElementById("feeding"),f=-1;null!==b&&(f=b.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||
-1!==f||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(g,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(doEatNorm,a),a+=getRandomPause(longPause1,longPause2),setTimeout(c,a))}function g(){if(20>document.getElementById("energie").innerHTML){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,
shortPause2),setTimeout(f,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(g,a))}else a=getRandomPause(shortPause1,shortPause2),setTimeout(f,a)}function f(){var a=document.getElementsByClassName("action action-style-4 coucher-box action-disabled"),b=document.getElementsByClassName("action action-style-4 coucher action-disabled");void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,
longPause2),setTimeout(pauseFunc,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a))}var h=getRandomPause(shortPause1,shortPause2);setTimeout(a,h)}
function MyTrain(){16<chevalAge&&22>=chevalAge?(OatsToGive=12,Walks1(walk1)):100>getMyParameterByName(train2+"TComplet")?(OatsToGive=12,HayToGive=14,Train(train2)):void 0===document.getElementsByClassName("action action-style-4 competition-galop action")[0]?EquipAmunition():100>getMyParameterByName(train1+"TComplet")?(OatsToGive=12,Train(train1)):100>getMyParameterByName(walk1+"Complet")?(HayToGive=12,OatsToGive=14,Walks(walk1)):compComplet?100>getMyParameterByName(train3+"TComplet")?(OatsToGive=
12,HayToGive=14,Train(train3)):124>chevalAge?(HayToGive=12,OatsToGive=14,setTimeout(function(){walk(walk2)},400),setTimeout(drink,1E3),setTimeout(function(){ORProg()},1300)):"feminin"===chevalSexe?BirthProg():"masculin"===chevalSexe&&parseInt(readCookie(offers),10)<offersToBeDone?GiveOfferings(5):"masculin"===chevalSexe&&parseInt(readCookie(offers),10)===offersToBeDone&&(eraseCookie(offers),GoToMother()):(HayToGive=-1,OatsToGive=10,CompNoVIP())}
function zeus(){var a=/id=([^&]+)/i.exec(document.location.search)[1];window.location="http://www.lowadi.com/marche/noir/object?qName=eclair-zeus&cheval="+a}function doR(){document.getElementsByClassName("button button-style-2")[0].click()}function st(){var a=document.getElementById("inventaire-utilisation-standard");null!==a&&a.click()}
function GiveOfferings(a){function b(){var e=document.getElementsByClassName("action action-style-4 panser action-disabled"),a=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==e[0]||void 0!==a[0]?(e=getRandomPause(shortPause1,shortPause2),setTimeout(c,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(groom,e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,e))}function c(){if(800<timeConvert()&&1200>timeConvert()){var a=getRandomPause(shortPause1,
shortPause2);setTimeout(function(){competitionByName1()},a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(c,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(g,a)}function g(){if(540>timeConvert()){var a=getRandomPause(shortPause1,shortPause2);setTimeout(giveOfferForTeam,a);a+=getRandomPause(2*longPause1,2*longPause2);setTimeout(g,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(f,a)}function f(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),
l=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(h,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a))}function h(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled");void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||
void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(openFeeding,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(doEatDef,a),a+=getRandomPause(longPause1,longPause2),setTimeout(h,a))}function k(){if(22<document.getElementById("energie").innerHTML&&800>timeConvert()){var a=getRandomPause(shortPause1,shortPause2);setTimeout(giveOfferForTeam,a);a+=getRandomPause(3*longPause1,3*longPause2);setTimeout(k,a)}else a=getRandomPause(shortPause1,
shortPause2),setTimeout(m,a)}function m(){var e=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");1100<timeConvert()||void 0!==e[0]||void 0!==l[0]||(console.log("offers="+readCookie(offers)),createCookie(offers,parseInt(readCookie(offers),10)+a),console.log("offers="+readCookie(offers)));e=getRandomPause(shortPause1,shortPause2);setTimeout(n,e)}function n(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),
l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementsByClassName("action action-style-4 carotte action-disabled"),l=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0!==
a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a))}function q(){var a=document.getElementsByClassName("action action-style-4 carotte action-disabled"),l=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled"),b=document.getElementsByClassName("action action-style-4 coucher-box action-disabled");void 0===b[0]||void 0===
a[0]&&void 0===l[0]||parseInt(readCookie(offers),10)!==offersToBeDone?void 0===b[0]||void 0===a[0]&&void 0===l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(3*longPause1,3*longPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(3*longPause1,3*longPause2),setTimeout(pauseFunc,a)):(eraseCookie(offers),GoToMother())}var r=getRandomPause(shortPause1,shortPause2);setTimeout(b,r)}
function GoToMother(){var a=document.getElementsByClassName("horsename")[1].href;document.location.replace("http://www.lowadi.com/elevage/chevaux/cheval?id="+a.substring(a.search("=")+1))}
function giveOfferForTeam(){var a=0+getRandomPause(mediumPause1,mediumPause2);setTimeout(openReproduction,a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(selectTeamOffers,a);var b=a+getRandomPause(mediumPause1,mediumPause2);setTimeout(doOffer,b);a+=getRandomPause(longPause1,longPause2);setTimeout(pauseFunc,a)}function selectTeamOffers(){document.getElementById("formMalePublicTypeEquipe").click()}function doOffer(){document.getElementById("boutonMaleReproduction").click()}
function timeConvert(){var a=document.getElementsByClassName("hour").item(0).innerHTML,b=parseInt(a.substring(0,3));a=parseInt(a.substring(3));return 60*b+a}
function BirthProg(){console.log(doAbort+"="+readCookie(doAbort));var a=null!==document.getElementById("alerteVeterinaireContent")&&(0===readCookie(doAbort)||chevalAge>mol);console.log("\u0423\u0441\u043b\u043e\u0432\u0438\u0435 \u0440\u043e\u0434\u0438\u0442\u044c = "+a);a?document.getElementById("lienVeterinaire").click():800<timeConvert()?(a=getRandomPause(mediumPause1,mediumPause2),setTimeout(ORProg,a)):0===nav?(a=getRandomPause(shortPause1,shortPause2),setTimeout(openReproduction,a),a+=getRandomPause(mediumPause1,
mediumPause2),setTimeout(Train1,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(openReproduction,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(ORProg,a))}
function Train1(){void 0!==document.getElementsByClassName("action action-style-4 competition-galop action-disabled")[0]?ORProg():100>getMyParameterByName(walk2+"Complet")?(HayToGive=14,OatsToGive=12,WalksBirth(walk2)):100>getMyParameterByName("enduranceTComplet")?(OatsToGive=12,HayToGive=-1,Train("endurance")):100>getMyParameterByName("galopTComplet")?(OatsToGive=12,Train("galop")):100>getMyParameterByName("sautTComplet")?(OatsToGive=12,Train("saut")):ORProg()}
function openReproduction(){if(null!==document.getElementById("reproduction-bottom")){var a=document.getElementById("reproduction-tab-0").getElementsByTagName("a")[1];a.click();if(-1!=a.className.indexOf("action action-style-4 echographie")){var b="";a=getRandomPause(shortPause1,shortPause2);setTimeout(function(){var a=document.getElementById("reproduction-tab-1").getElementsByClassName("col-1");console.log(a);a=a[0].childNodes[0].nodeValue;console.log(a);b=-1!=a.indexOf("\u0436\u0435\u0440\u0435\u0431")?
"masculin":"feminin";console.log("childSexe="+b);lParentSex=getLastParentSexForBirth();console.log("!!getLastParentSexForBirth="+getLastParentSexForBirth());lParentSex===b?createCookie(doAbort,1):createCookie(doAbort,0);console.log("openReproduction/doAbort="+readCookie(doAbort))},a)}}}function reserve(){"tab-style-6-0-0 selected"!=document.getElementById("tab-1").className&&document.getElementsByClassName("tab-action")[1].click()}
function doReproduction(){var a=document.getElementsByClassName("button button-style-0");document.getElementById("race").options[22].selected=!0;document.getElementById("race").options[22].selected=!0;a.item(0).click()}function doReproduction2(){document.getElementsByClassName("button button-style-0")[1].click()}
if(/www.lowadi.com\/elevage\/chevaux\/choisirNoms\?jument=/.test(window.location.href)){-1!==document.body.innerHTML.indexOf("femelle_v1828806360.png")?document.getElementById("poulain-1").setAttribute("value","\u041a\u043e\u0431\u044b\u043b\u0430"):document.getElementById("poulain-1").setAttribute("value","\u0416\u0435\u0440\u0435\u0431\u0435\u043d\u043e\u043a");var d=document.getElementsByTagName("button");"submit"==d[d.length-1].getAttribute("type")&&d[d.length-1].click()}
/www.lowadi.com\/elevage\/chevaux\/saillie\?offre=/.test(window.location.href)&&(pause=getRandomPause(longPause1,longPause2),setTimeout(function(){document.getElementById("boutonDoReproduction").click()},pause));
if(/www.lowadi.com\/elevage\/chevaux\/rechercherMale\?jument=/.test(window.location.href)){pause=getRandomPause(2*longPause1,2*longPause2);setTimeout(reserve,pause);pause1=pause+getRandomPause(2*longPause1,2*longPause2);setTimeout(doReproduction,pause1);var pause2=pause1+getRandomPause(2*longPause1,2*longPause2);setTimeout(doReproduction2,pause2)}function loadURL(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText}
function getGenetics(a){document.getElementById("tab-genetics-title").onclick();return document.getElementById(a).childNodes[0].nodeValue}
function getLastParent(){if(""===lastParentPage){var a=document.getElementsByClassName("horsename");console.log(a);var b=a[0].href.substring(a[0].href.search("=")+1);a=a[a.length-1].href.substring(a[a.length-1].href.search("=")+1);b>a?(lastParentPage="",lastParentPage=loadURL("http://www.lowadi.com/elevage/fiche/?id="+b)):(lastParentPage="",lastParentPage=loadURL("http://www.lowadi.com/elevage/fiche/?id="+a))}return lastParentPage}
function getLastParentSex(){var a=document.getElementById("tab-genetics").getElementsByClassName("horsename"),b=a[0].href.substring(a[0].href.search("=")+1);a=a[a.length-1].href.substring(a[a.length-1].href.search("=")+1);console.log(b+";"+a+";"+chevalId);return lastParentSex=b>a?"masculin":"feminin"}
function getLastParentSexForBirth(){var a=document.getElementById("reproduction").getElementsByClassName("horsename");console.log(a);a=a[0].href.substring(a[0].href.search("=")+1);console.log("d0="+a+"; d="+chevalId);lastParentSexForBirth=chevalId>a?"feminin":"masculin";console.log("lastParentSexForBirth="+lastParentSexForBirth);return lastParentSexForBirth}function getLastParentGenetics(a){var b=getLastParent();a=b.substring(b.search(a)+a.length+2);return a.substring(0,a.search("<"))}
function Walks(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),l=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){var a=document.getElementById("moral").textContent,l=document.getElementsByClassName("action action-style-4 boire action-disabled"),
b=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");99<a||void 0!==l[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(g,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,a))}function g(){if(840>timeConvert()){var a=getRandomPause(shortPause1,shortPause2);setTimeout(function(){competitionByNameVIP(compName)},a);a+=getRandomPause(longPause1,longPause2);setTimeout(g,
a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(f,a)}function f(){if(void 0!==document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(h,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a)}function h(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),l=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");
void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(h,a))}function k(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),l=document.getElementById("feeding"),b=-1;null!==l&&(b=l.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||
-1!==b||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(m,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(doEatDef,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,a))}function m(){var e=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte action-disabled"),c=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled"),
r=document.getElementById("energie").innerHTML;void 0!==e[0]||void 0!==l[0]||void 0!==b[0]||void 0!==c[0]||10>r||1300<timeConvert()?(e=getRandomPause(shortPause1,shortPause2),setTimeout(n,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk(a)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,e))}function n(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");
void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementsByClassName("action action-style-4 carotte action-disabled"),l=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,
shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a))}function q(){if(void 0!==document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(OR,a);a+=getRandomPause(longPause1,longPause2);setTimeout(pauseFunc,a);a+=getRandomPause(3*longPause1,3*longPause2);setTimeout(reload,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,
mediumPause2),setTimeout(q,a)}var r=getRandomPause(shortPause1,shortPause2);setTimeout(b,r)}
function WalksBirth(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),l=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){if(600<timeConvert()||36<chevalAge){var e=getRandomPause(shortPause1,
shortPause2);setTimeout(g,e)}else e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk00(a,5)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,e)}function g(){if(655<timeConvert()){var e=getRandomPause(shortPause1,shortPause2);setTimeout(f,e)}else e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk00(a,4)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(g,e)}function f(){if(void 0!==document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=
getRandomPause(shortPause1,shortPause2);setTimeout(h,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a)}function h(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),l=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),
setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(h,a))}function k(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),l=document.getElementById("feeding"),b=-1;null!==l&&(b=l.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||-1!==b||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(m,a)):(a=getRandomPause(shortPause1,
shortPause2),setTimeout(doEatDef,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,a))}function m(){var e=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte action-disabled"),c=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled"),r=document.getElementById("energie").innerHTML;
void 0!==e[0]||void 0!==l[0]||void 0!==b[0]||void 0!==c[0]||10>r||1320<timeConvert()?(e=getRandomPause(shortPause1,shortPause2),setTimeout(n,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk(a)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,e))}function n(){document.getElementById("energie");var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");
void 0!==a[0]||void 0!==l[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementById("energie").innerHTML,l=document.getElementsByClassName("action action-style-4 carotte action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0!==l[0]||void 0!==b[0]||20<a?(a=getRandomPause(shortPause1,
shortPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a))}function q(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),l=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0===document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]||void 0===a[0]&&void 0===l[0]?(a=getRandomPause(shortPause1,
shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,longPause2),setTimeout(pauseFunc,a),a+=getRandomPause(2*longPause1,2*longPause2),setTimeout(reload,a))}var r=getRandomPause(shortPause1,shortPause2);setTimeout(b,r)}
function Walks1(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),e=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){if(600<timeConvert()||36<chevalAge){var e=getRandomPause(shortPause1,
shortPause2);setTimeout(g,e)}else e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk00(a,5)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,e)}function g(){if(600>timeConvert()&&36<chevalAge){var a=getRandomPause(shortPause1,shortPause2);setTimeout(function(){competitionByNameVIP(compName)},a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(g,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(f,a)}function f(){if(655<timeConvert()){var e=getRandomPause(shortPause1,
shortPause2);setTimeout(h,e)}else e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk00(a,4)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,e)}function h(){if(void 0!==document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(k,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(h,a)}function k(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),
e=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(m,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,a))}function m(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),e=document.getElementById("feeding"),b=-1;null!==e&&(b=e.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));
void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||-1!==b||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(n,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(doEatDef,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,a))}function n(){var e=document.getElementsByClassName("action action-style-4 caresser action-disabled"),b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled"),
c=document.getElementsByClassName("action action-style-4 carotte action-disabled"),r=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled"),q=document.getElementById("energie").innerHTML;void 0!==e[0]||void 0!==b[0]||void 0!==c[0]||void 0!==r[0]||10>q||1320<timeConvert()?(e=getRandomPause(shortPause1,shortPause2),setTimeout(p,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk(a)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,
e))}function p(){document.getElementById("energie");var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),e=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a))}function q(){var a=document.getElementById("energie").innerHTML,
e=document.getElementsByClassName("action action-style-4 carotte action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0!==e[0]||void 0!==b[0]||20<a?(a=getRandomPause(shortPause1,shortPause2),setTimeout(r,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(q,a))}function r(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),e=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");
void 0===document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]||void 0===a[0]&&void 0===e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(r,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,longPause2),setTimeout(pauseFunc,a),a+=getRandomPause(2*longPause1,2*longPause2),setTimeout(reload,a))}var e=getRandomPause(shortPause1,shortPause2);setTimeout(b,
e)}
function walk00(a,b){document.getElementById("energie");var c=timeConvert();c=Math.floor((1360-c)/30);switch(a){case "foret":var g=document.getElementById("walkforetSlider").getElementsByTagName("li");var f=document.getElementById("walkforetSlider-sliderHidden");var h=document.getElementById("walk-foret-submit");break;case "montagne":g=document.getElementById("walkmontagneSlider").getElementsByTagName("li"),f=document.getElementById("walkmontagneSlider-sliderHidden"),h=document.getElementById("walk-montagne-submit")}for(c=trainTime=
b<=c?b:c;0<=c;c--)if("green hiddenNumber disabled"!==g[c].className&&"green disabled"!==g[c].className){g[c].className+=" selected";g[c].click();f.value=c;g[c].click();h.click();break}}
function walk(a){document.getElementById("energie");var b=timeConvert();b=Math.floor((1380-b)/30);switch(a){case "foret":var c=document.getElementById("walkforetSlider").getElementsByTagName("li");var g=document.getElementById("walkforetSlider-sliderHidden");var f=document.getElementById("walk-foret-submit");break;case "montagne":c=document.getElementById("walkmontagneSlider").getElementsByTagName("li"),g=document.getElementById("walkmontagneSlider-sliderHidden"),f=document.getElementById("walk-montagne-submit")}for(a=
20<=b?20:b;0<=a;a--)if("green hiddenNumber disabled"!==c[a].className&&"green disabled"!==c[a].className){c[a].className+=" selected";c[a].click();g.value=a;c[a].click();f.click();break}}function Train(a){switch(a){case "dressage":Train9(a);break;case "saut":Train3(a);break;case "vitesse":case "trot":Train7(a);break;case "endurance":Train3(a);break;case "galop":Train3(a)}}
function Train9(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),r=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==r[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){var a=document.getElementById("energie").textContent;if(90>a&&670<
timeConvert())a=getRandomPause(shortPause1,shortPause2),setTimeout(g,a);else{var b=getMyParameterByName("dressageTComplet");96>b?(a=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train("dressage",12)},a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,a)):95<b&&670>timeConvert()&&95<b&&20<a?(a=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train("dressage",4)},a),a+=getRandomPause(longPause1,longPause2),setTimeout(function(){train("vitesse",3)},a),a+=getRandomPause(mediumPause1,
mediumPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(g,a))}}function g(){if(void 0!==document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(f,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(g,a)}function f(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),b=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");
void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(h,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a))}function h(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),b=document.getElementById("feeding"),e=-1;null!==b&&(e=b.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||
-1!==e||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(doEatDef,a),a+=getRandomPause(longPause1,longPause2),setTimeout(h,a))}function k(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled"),e=document.getElementById("energie").textContent;30>e||void 0!==a[0]||void 0!==b[0]||1230<timeConvert()?
(e=getRandomPause(shortPause1,shortPause2),setTimeout(m,e)):(a=getMyParameterByName("vitesseTComplet"),100>a?(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train("vitesse",12)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,e)):100==a&&1150>timeConvert()&&100==a&&20<e?(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){walk(walk2)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(m,e)))}
function m(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(n,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,a))}function n(){var a=document.getElementById("energie").textContent,b=document.getElementsByClassName("action action-style-4 carotte action-disabled"),
e=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");19<a||void 0!==b[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");
void 0===document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]||void 0===a[0]&&void 0===b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,longPause2),setTimeout(pauseFunc,a),a+=getRandomPause(2*longPause1,2*longPause2),setTimeout(reload,a))}a=getRandomPause(shortPause1,shortPause2);setTimeout(b,a)}
function Train7(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),e=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){if(70>document.getElementById("energie").textContent){var b=getRandomPause(shortPause1,
shortPause2);setTimeout(g,b)}else b=getMyParameterByName(a+"TComplet"),93>=b?(b=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train(a,5)},b),b+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,b)):93<b?(b=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train(a,6)},b),b+=getRandomPause(longPause1,longPause2),setTimeout(c,b)):(b=getRandomPause(shortPause1,shortPause2),setTimeout(g,b))}function g(){if(void 0!==document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=
getRandomPause(shortPause1,shortPause2);setTimeout(f,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(g,a)}function f(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),e=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(h,a)):(a=getRandomPause(shortPause1,shortPause2),
setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a))}function h(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),e=document.getElementById("feeding"),b=-1;null!==e&&(b=e.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||-1!==b||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,
shortPause2),setTimeout(doEatDef,a),a+=getRandomPause(longPause1,longPause2),setTimeout(h,a))}function k(){var b=document.getElementsByClassName("action action-style-4 caresser action-disabled"),e=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled"),c=document.getElementById("energie").textContent;(15>c||void 0!==b[0]||void 0!==e[0])&&1260<timeConvert()?(c=getRandomPause(shortPause1,shortPause2),setTimeout(m,c)):(b=getMyParameterByName(a+"TComplet"),93>=b&&1261>
timeConvert()&&19<c?(c=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train(a,20)},c),c+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,c)):93<b&&1261>timeConvert()&&93<b&&20<c?(c=getRandomPause(shortPause1,shortPause2),setTimeout(function(){competitionByName1()},c),c+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,c)):(c=getRandomPause(shortPause1,shortPause2),setTimeout(m,c)))}function m(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),
e=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(n,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,a))}function n(){var a=document.getElementById("energie").textContent,e=document.getElementsByClassName("action action-style-4 carotte action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");
19<a||void 0!==e[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),e=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0===document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]||
void 0===a[0]&&void 0===e[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,longPause2),setTimeout(pauseFunc,a),a+=getRandomPause(2*longPause1,2*longPause2),setTimeout(reload,a))}var q=getRandomPause(shortPause1,shortPause2);setTimeout(b,q)}
function Train3(a){function b(){var a=document.getElementsByClassName("action action-style-4 panser action-disabled"),f=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==a[0]||void 0!==f[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(groom,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){var e=document.getElementById("energie").textContent;if(590<timeConvert())e=
getRandomPause(shortPause1,shortPause2),setTimeout(g,e);else{var b=getMyParameterByName(a+"TComplet");94>b?(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train(a,7)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,e)):93<b&&600>timeConvert()&&93<b&&20<e?(e=getRandomPause(shortPause1,shortPause2),setTimeout(function(){train(a,6)},e),e+=getRandomPause(mediumPause1,mediumPause2),setTimeout(c,e)):(e=getRandomPause(shortPause1,shortPause2),setTimeout(g,e))}}function g(){if(void 0!==
document.getElementsByClassName("action action-style-4 mash action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(f,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(mash,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(g,a)}function f(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),b=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,
shortPause2),setTimeout(h,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(f,a))}function h(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled"),b=document.getElementById("feeding"),c=-1;null!==b&&(c=b.innerHTML.indexOf("\u0442\u043e\u043b\u0441\u0442"));void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||-1!==c||void 0!==a[0]?
(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(openFeeding,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(doEatDef,a),a+=getRandomPause(longPause1,longPause2),setTimeout(h,a))}function k(){var b=document.getElementById("energie").textContent,c=Math.floor(10*b/63),f=getMyParameterByName(a+"TComplet");30>b||1100<timeConvert()||91<f?(b=getRandomPause(shortPause1,shortPause2),setTimeout(m,b)):(b=getRandomPause(shortPause1,
shortPause2),setTimeout(function(){train(a,c)},b),b+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,b))}function m(){var b=document.getElementById("energie").textContent,c=getMyParameterByName(a+"TComplet");20>b||1200<timeConvert()||92>c?(b=getRandomPause(shortPause1,shortPause2),setTimeout(n,b)):(b=getRandomPause(shortPause1,shortPause2),setTimeout(function(){competitionByName1()},b),b+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,b))}function n(){var a=document.getElementsByClassName("action action-style-4 caresser action-disabled"),
b=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");void 0!==a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(p,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(n,a))}function p(){var a=document.getElementsByClassName("action action-style-4 carotte action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0!==
a[0]||void 0!==b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(p,a))}function q(){var a=document.getElementsByClassName("action action-style-4 carotte action-disabled"),b=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");void 0===document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]||void 0===
a[0]&&void 0===b[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(q,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(OR,a),a+=getRandomPause(longPause1,longPause2),setTimeout(pauseFunc,a))}var r=getRandomPause(shortPause1,shortPause2);setTimeout(b,r)}
function train(a,b){var c,g=timeConvert();g=Math.floor((1360-g)/30);switch(a){case "endurance":var f=document.getElementById("trainingEnduranceSlider").getElementsByTagName("li");var h=document.getElementById("trainingEnduranceSlider-sliderHidden");var k=document.getElementById("training-endurance-submit");break;case "vitesse":f=document.getElementById("trainingVitesseSlider").getElementsByTagName("li");h=document.getElementById("trainingVitesseSlider-sliderHidden");k=document.getElementById("training-vitesse-submit");
break;case "dressage":f=document.getElementById("trainingDressageSlider").getElementsByTagName("li");h=document.getElementById("trainingDressageSlider-sliderHidden");k=document.getElementById("training-dressage-submit");break;case "galop":f=document.getElementById("trainingGalopSlider").getElementsByTagName("li");h=document.getElementById("trainingGalopSlider-sliderHidden");k=document.getElementById("training-galop-submit");break;case "trot":f=document.getElementById("trainingTrotSlider").getElementsByTagName("li");
h=document.getElementById("trainingTrotSlider-sliderHidden");k=document.getElementById("training-trot-submit");break;case "saut":f=document.getElementById("trainingSautSlider").getElementsByTagName("li"),h=document.getElementById("trainingSautSlider-sliderHidden"),k=document.getElementById("training-saut-submit")}for(b<=g?c=b:b>g&&(c=g);0<=c;c--)if("green hiddenNumber disabled"!==f[c].className&&"green disabled"!==f[c].className){f[c].className+=" selected";f[c].click();h.value=c;f[c].click();k.click();
break}}function EquipAmunition(){var a=pause+getRandomPause(mediumPause1,mediumPause2);setTimeout(specialization,a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(amunition1,a);a+=getRandomPause(3*mediumPause1,3*mediumPause2);setTimeout(amunition2,a)}function specialization(){document.getElementById(specialisation).getElementsByTagName("button")[0].click();setTimeout(function(){location.reload()},1500)}
function amunition1(){var a=document.getElementById("competition-body-content").getElementsByTagName("a");console.log(a[0]);a[0].click()}function amunitionById(a){document.getElementById(a).click()}
function amunition2(){var a=0+getRandomPause(4*mediumPause1,4*mediumPause2);setTimeout(function(){amunitionById("modele-tapis-"+amSpecialisation+"-1x")},a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(function(){amunitionById("modele-selle-"+amSpecialisation+"-1x")},a);a+=getRandomPause(mediumPause1,mediumPause2);setTimeout(function(){amunitionById("modele-bride-"+amSpecialisation+"-1x")},a);var b=a+getRandomPause(mediumPause1,mediumPause2);setTimeout(function(){var a=document.getElementById("choisir-equipement-popup-content").getElementsByTagName("button");
console.log(a[a.length-1]);a[a.length-1].click();void 0===document.getElementsByClassName("action action-style-4 competition-galop action")[0]&&(getRandomPause(10*shortPause1,10*shortPause1),setTimeout(function(){location.reload()},b))},b)}
if(/www.lowadi.com\/elevage\/competition\/inscription\?cheval=/.test(window.location.href)){pause2=getRandomPause(2*mediumPause1,2*mediumPause2);setTimeout(competitionInscript,pause2);var pause3=pause2+getRandomPause(4*mediumPause1,4*mediumPause2);setTimeout(competitionInscript,pause3);var pause4=pause2+getRandomPause(6*mediumPause1,6*mediumPause2);setTimeout(checkComp,pause4)}function competitionInscript(){document.getElementsByClassName("button button-style-0").item(0).click()}
function checkComp(){void 0!==document.getElementsByClassName("fieldErrorText into")[0]&&location.reload()}function competitionByName1(){compComplet||competitionByNameVIP("trot")}function competitionByName(a){a=document.getElementsByClassName("action action-style-4 competition-"+a);document.location.replace(a.item(0).href)}function competitionByNameVIP(a){document.getElementsByClassName("action action-style-4 competition-"+a).item(0).click()}
function CompNoVIP(){function a(){var c=document.getElementsByClassName("action action-style-4 panser action-disabled"),f=document.getElementsByClassName("action action-style-4 panser-rainbow action-disabled");void 0!==c[0]||void 0!==f[0]?(c=getRandomPause(shortPause1,shortPause2),setTimeout(b,c)):(c=getRandomPause(shortPause1,shortPause2),setTimeout(groom,c),c+=getRandomPause(mediumPause1,mediumPause2),setTimeout(a,c))}function b(){var a=document.getElementsByClassName("action action-style-4 boire action-disabled"),
f=document.getElementsByClassName("action action-style-4 boire-fontaine action-disabled");void 0!==a[0]||void 0!==f[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(c,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(drink,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(b,a))}function c(){if(700>timeConvert()){var a=getRandomPause(shortPause1,shortPause2);setTimeout(function(){competitionByName1()},a);a+=getRandomPause(longPause1,longPause2);setTimeout(c,a)}else a=getRandomPause(shortPause1,
shortPause2),setTimeout(g,a)}function g(){var a=document.getElementsByClassName("action action-style-4 allaiter action-disabled");void 0!==document.getElementsByClassName("tab-action tab-action-select action action-style-4 nourrir-entame")[0]||void 0!==a[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(f,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(openFeeding,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(doEatDef,a),a+=getRandomPause(longPause1,longPause2),setTimeout(g,
a))}function f(){if(1290>timeConvert()){var a=getRandomPause(shortPause1,shortPause2);setTimeout(function(){competitionByNameVIP("trot")},a);a+=getRandomPause(longPause1,longPause2);setTimeout(f,a)}else a=getRandomPause(shortPause1,shortPause2),setTimeout(h,a)}function h(){var a=document.getElementById("energie").textContent,b=document.getElementsByClassName("action action-style-4 caresser action-disabled"),c=document.getElementsByClassName("action action-style-4 caresser-rainbow action-disabled");
20<a||void 0!==b[0]||void 0!==c[0]?(a=getRandomPause(shortPause1,shortPause2),setTimeout(k,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(stroke,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(h,a))}function k(){var a=document.getElementById("energie").textContent,b=document.getElementsByClassName("action action-style-4 carotte action-disabled"),c=document.getElementsByClassName("action action-style-4 carotte-rainbow action-disabled");20<a||void 0!==b[0]||void 0!==c[0]?(a=getRandomPause(shortPause1,
shortPause2),setTimeout(m,a)):(a=getRandomPause(shortPause1,shortPause2),setTimeout(carrot,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(k,a))}function m(){if(void 0!==document.getElementsByClassName("action action-style-4 coucher-box action-disabled")[0]){var a=getRandomPause(shortPause1,shortPause2);setTimeout(OR,a);a+=getRandomPause(longPause1,longPause2);setTimeout(pauseFunc,a);a+=getRandomPause(2*longPause1,2*longPause2);setTimeout(reload,a)}else a=getRandomPause(shortPause1,shortPause2),
setTimeout(sleep,a),a+=getRandomPause(mediumPause1,mediumPause2),setTimeout(m,a)}var n=getRandomPause(shortPause1,shortPause2);setTimeout(a,n)}
function doEatDef(){var a=!1,b=document.getElementById("feeding").innerHTML;var c=-1===HayToGive?hayToGive():HayToGive;var g=-1===OatsToGive?oatsToGive():OatsToGive;if(0!==c+g){-1!==b.indexOf("\u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u044b\u0439")&&(c=20-hayGiven(),g=15-oatsGiven());if(-1!==b.indexOf("haySlider")){var f=document.getElementById("haySlider").getElementsByTagName("li");a=c;f[a].className+=" selected";f[a].click();f=document.getElementById("haySlider-sliderHidden");
f.setAttribute("value",a);a=!0}-1!==b.indexOf("oatsSlider")&&(f=document.getElementById("oatsSlider").getElementsByTagName("li"),a=g,f[a].className+=" selected",f[a].click(),f=document.getElementById("oatsSlider-sliderHidden"),f.setAttribute("value",a),a=!0);!1===a&&(-1!==b.indexOf('id="feedingHay"')&&(document.getElementById("feedingHay").options[c].selected=!0),-1!==b.indexOf('id="feedingOats"')&&(document.getElementById("feedingOats").options[g].selected=!0));b=document.getElementById("feed-button");
null!==b&&b.click()}}
function doEatPre(){if(-1!==document.body.innerHTML.indexOf("boutonAllaiter"))document.getElementById("boutonAllaiter").click();else{var a=!1,b=document.getElementById("feeding").innerHTML,c=hayToGive(),g=oatsToGive();if(0!==c+g&&-1===b.indexOf("\u0442\u043e\u043b\u0441\u0442")){-1!==b.indexOf("\u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u044b\u0439")&&(c=20-hayGiven(),g=15-oatsGiven());if(-1!==b.indexOf("haySlider")){var f=document.getElementById("haySlider").getElementsByTagName("li");a=
c;f[a].className+=" selected";f[a].click();f=document.getElementById("haySlider-sliderHidden");f.setAttribute("value",a);a=!0}-1!==b.indexOf("oatsSlider")&&(f=document.getElementById("oatsSlider").getElementsByTagName("li"),a=g,f[a].className+=" selected",f[a].click(),f=document.getElementById("oatsSlider-sliderHidden"),f.setAttribute("value",a),a=!0);!1===a&&(-1!==b.indexOf('id="feedingHay"')&&(document.getElementById("feedingHay").options[c].selected=!0),-1!==b.indexOf('id="feedingOats"')&&(document.getElementById("feedingOats").options[g].selected=
!0))}}}
function doEatNorm(){if(-1!==document.body.innerHTML.indexOf("boutonAllaiter"))document.getElementById("boutonAllaiter").click();else{var a=!1,b=document.getElementById("feeding").innerHTML,c=hayToGive(),g=oatsToGive();if(0!==c+g&&-1===b.indexOf("\u0442\u043e\u043b\u0441\u0442")){-1!==b.indexOf("\u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u044b\u0439")&&(c=20-hayGiven(),g=15-oatsGiven());if(-1!==b.indexOf("haySlider")){var f=document.getElementById("haySlider").getElementsByTagName("li");a=
c;f[a].className+=" selected";f[a].click();f=document.getElementById("haySlider-sliderHidden");f.setAttribute("value",a);a=!0}-1!==b.indexOf("oatsSlider")&&(f=document.getElementById("oatsSlider").getElementsByTagName("li"),a=g,f[a].className+=" selected",f[a].click(),f=document.getElementById("oatsSlider-sliderHidden"),f.setAttribute("value",a),a=!0);!1===a&&(-1!==b.indexOf('id="feedingHay"')&&(document.getElementById("feedingHay").options[c].selected=!0),-1!==b.indexOf('id="feedingOats"')&&(document.getElementById("feedingOats").options[g].selected=
!0));b=document.getElementById("feed-button");null!==b&&b.click()}}}function hayToGive(){var a=1*hayNorm()-1*hayGiven();0>a&&(a=0);20<a&&(a=20);return a}function oatsToGive(){if(-1!==document.getElementById("feeding").outerHTML.indexOf("oats")||-1!==document.getElementById("feeding").outerHTML.indexOf("Oats")){var a=1*oatsNorm()-1*oatsGiven();0>a&&(a=0);15<a&&(a=15);return a}return 0}
function hayNorm(){return document.getElementsByClassName("section-fourrage section-fourrage-target")[0].childNodes[0].nodeValue}function hayGiven(){var a=document.getElementsByClassName("float-right section-fourrage section-fourrage-quantity")[0].outerHTML;return a.substring(a.indexOf("/ <strong class")-3,a.lastIndexOf("/ <strong class"))}function oatsNorm(){return document.getElementsByClassName("section-avoine section-avoine-target")[0].childNodes[0].nodeValue}
function oatsGiven(){var a=document.getElementsByClassName("float-right section-avoine section-avoine-quantity")[0].outerHTML;return a.substring(a.indexOf("/ <strong class")-3,a.lastIndexOf("/ <strong class"))}function reload(){location.reload()}function groom(){var a=document.getElementById("boutonPanser");null!==a&&a.click()}function sleep(){var a=document.getElementById("boutonCoucher");null!==a&&a.click()}function stroke(){var a=document.getElementById("boutonCaresser");null!==a&&a.click()}
function carrot(){var a=document.getElementById("boutonCarotte");null!==a&&a.click()}function drink(){var a=document.getElementById("boutonBoire");null!==a&&a.click()}function mash(){var a=document.getElementById("boutonMash");null!==a&&a.click()}function prev(){var a=document.getElementById("nav-previous");null!==a&&a.hasAttribute("href")&&a.click()}function OR(){var a=document.getElementById("age").getElementsByTagName("button");null!==a[0]&&a[0].click()}
function giveName(){var a=0+getRandomPause(shortPause1,shortPause2);setTimeout(function(){document.getElementById("widget--1").click()},a);a+=getRandomPause(shortPause1/4,shortPause2/4);setTimeout(function(){document.getElementsByClassName("options-menu")[0].getElementsByClassName("first")[0].getElementsByTagName("a")[2].click()},a);a+=getRandomPause(shortPause1,shortPause2);setTimeout(function(){var a=document.getElementById("horseNameName");(""+getMyParameterByName(genetics[0])).split(".");a.value=
("masculin"===chevalSexe?polM:polJ)+" "+(enduranceGenetique+vitesseGenetique+dressageGenetique+galopGenetique+trotGenetique+sautGenetique).toFixed(2)},a);a+=getRandomPause(shortPause1/4,shortPause2/4);setTimeout(function(){document.getElementById("horseNameAffixe").getElementsByTagName("optgroup")[1].getElementsByTagName("option")[0].setAttribute("selected","selected")},a);a+=getRandomPause(shortPause1,shortPause2);setTimeout(function(){document.getElementById("profil-popup-content").getElementsByClassName("spacer-small-top button button-style-0")[0].click()},
a)}function createCookie(a,b){document.cookie=a+"="+b+";expires: 800 "}function readCookie(a){a=("; "+document.cookie).split("; "+a+"=");if(2===a.length)return a.pop().split(";").shift()}function eraseCookie(a){createCookie(a,";expires: -1")}function getGlobalParameterByName(a){return window[a]}function getMyParameterByName(a){var b="";try{b=eval(a)}catch(c){}return b}function pauseFunc(){document.body.innerHTML.indexOf("chevalId")}function trim(a,b){return ltrim(rtrim(a,b),b)}
function ltrim(a,b){return a.replace(new RegExp("^["+(b||"\\s")+"] + ","g"),"")}function rtrim(a,b){return a.replace(new RegExp("["+(b||"\\s")+"] + $","g"),"")}function getRandomPause(a,b){return Math.random()*(b-a)+a}function openFeeding(){-1===document.body.innerHTML.indexOf("boutonAllaiter")&&document.getElementById("boutonNourrir").click()}
function eqCenterReg(){if(-1!==document.body.innerHTML.indexOf("cheval-inscription")){var a=document.getElementById("cheval-inscription").firstChild;null!==a&&a.click()}}/www.lowadi.com\/elevage\/chevaux\/centreInscription\?id=/.test(window.location.href)&&viborksk();
function \u043a\u0441\u043a\u0440\u0435\u0437\u0435\u0440\u0432(){var a=0+getRandomPause(2200,2600);setTimeout(eqCenterReg2,a);a+=getRandomPause(2800,3200);setTimeout(eqCenterReg3,a);a+=getRandomPause(3500,3800);setTimeout(eqCenterReg4,a)}function eqCenterReg2(){var a=document.getElementById("tab-box-reserve").getElementsByTagName("a");console.log(a[0]);a[0].click()}
function eqCenterReg3(){for(var a=document.getElementById("boxContent").getElementsByTagName("tbody")[0].getElementsByTagName("tr"),b=1;b<a.length;b++)if(localisation=a[b].getElementsByClassName("align-left width-19")[0].getElementsByTagName("a")[0].className,localisation==="centerLocalisation "+centerLocalisation){var c=a[b].getElementsByClassName("align-center")[0].outerHTML,g=c.search("abreuvoir");if(0<g&&(c=c.substring(g),g=c.search("douche"),0<g))for(c=a[b].getElementsByClassName("align-center align-middle spacer-small-left spacer-small-right")[dl].getElementsByTagName("button"),
g=0;g<c.length;g++)if(void 0===a[b].getElementsByClassName("align-center align-middle spacer-small-left spacer-small-right")[dl].getElementsByClassName("disabled button button-style-8")[0]){c[g].click();return}}}function eqCenterReg4(){!0!==/message=centreOk/.test(window.location.href)&&location.reload()}
function ksk_ALL(){var a=0+getRandomPause(2E3,2500);setTimeout(\u041a\u0421\u041a_O,a);a+=getRandomPause(2E3,2800);setTimeout(\u041a\u0421\u041a1,a);a+=getRandomPause(2200,2800);setTimeout(\u041a\u0421\u041a2,a)}
function \u041a\u0421\u041a_O(){document.getElementById("abreuvoir").setAttribute("value","1");document.getElementById("douche").setAttribute("value","1");document.getElementById(spec).setAttribute("value","1");document.getElementsByClassName("module module-style-20 module-css").nextElementSibling[0].click()}function \u041a\u0421\u041a1(){var a=document.getElementsByClassName("grid-cell spacer-small-top spacer-small-bottom")[dl].getElementsByTagName("a");getRandomPause(1E3,1300);a[0].click()}
function \u041a\u0421\u041a2(){var a=document.getElementsByClassName("odd highlight")[0].getElementsByTagName("button")[dl];window.oldConfirm=window.confirm;window.confirm=function(){return!0};a.click();window.confirm=window.oldConfirm};
